-- 建立廣告橫幅表
CREATE TABLE IF NOT EXISTS promo_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    link_url TEXT,
    order_index INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 插入初始廣告
-- 注意：這只是佔位符，實際圖片需要由管理員上傳
INSERT INTO promo_banners (image_url, link_url, order_index)
VALUES 
('https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=1470', 'https://example.com/shop', 0),
('https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=1470', 'https://example.com/events', 1);
