-- 建立教練活動資料表
CREATE TABLE IF NOT EXISTS coach_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    content TEXT,
    image_url TEXT,
    link_url TEXT,
    label TEXT,
    category TEXT DEFAULT '其他',
    is_featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 關閉 RLS 以便測試環境下直接讀寫
ALTER TABLE coach_events DISABLE ROW LEVEL SECURITY;

-- 插入一些初始教練測試活動
INSERT INTO coach_events (title, subtitle, label, category, is_featured)
VALUES 
('2026 教練成長計劃', '參加活動 ‧ 累積 XP ‧ 解鎖更高等級', '精選活動', '其他', true),
('2026 台北健身大賽', '教練競技交流', '★ 教練限定', '競賽', false),
('進階肌力訓練工作坊', '認證課程 ‧ 8小時', '★ 教練限定', '課程', false);
