-- 1. 建立教練資料表
CREATE TABLE IF NOT EXISTS coaches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    tags TEXT[],
    bio TEXT,
    rating DECIMAL(2,1) DEFAULT 0.0,
    courses_count INT DEFAULT 0,
    students_count INT DEFAULT 0,
    phone TEXT,
    email TEXT,
    status TEXT DEFAULT '在職',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 建立活動資料表
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 建立請假申請表
CREATE TABLE IF NOT EXISTS leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coach_name TEXT NOT NULL,
    type TEXT,
    status TEXT DEFAULT '待審核',
    reason TEXT,
    substitute TEXT,
    affected_classes INT DEFAULT 0,
    duration TEXT,
    target_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 插入初始教練資料
INSERT INTO coaches (name, tags, bio, rating, courses_count, students_count, phone, email, status)
VALUES 
('林美華', ARRAY['瑜珈', '普拉提'], '擁有 10 年瑜珈教學經驗，國際認證瑜珈教師', 4.9, 128, 45, '0912-345-678', 'lmh@fitadmin.com', '實力'),
('王志明', ARRAY['重訓', '體適能'], '國家認證重訓教練，專注於功能性訓練', 4.8, 215, 62, '0923-456-789', 'wzm@fitadmin.com', '實力'),
('吳曉嵐', ARRAY['舞蹈', '肚皮舞'], '專業舞者出身，教學活潑生動', 4.6, 95, 30, '0956-789-012', 'wxl@fitadmin.com', '請假中');

-- 插入初始活動資料
INSERT INTO events (title, subtitle)
VALUES 
('JZ--健身教材', '10/14 | 健身 | JENZiQ'),
('三月份春季間跑', '日程 | 競賽 | JENZiQ'),
('皮拉提斯課', '課程 | 瑜珈健 | JENZiQ');

-- 插入初始請假資料
INSERT INTO leave_requests (coach_name, type, status, reason, substitute, affected_classes, duration, target_date)
VALUES 
('王志明', '病假', '待審核', '感冒發燒，醫師建議休息兩天，無法正常授課', '李建國', 2, '2天', '2026-03-05'),
('林美華', '事假', '待審核', '家中有急事需處理，申請一天事假', '吳曉嵐', 1, '1天', '2026-03-10');
