-- 建立據點資料表
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    map_url TEXT,
    hours TEXT,
    phone TEXT,
    tags TEXT[],
    is_featured BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 插入初始據點資料
INSERT INTO locations (name, address, map_url, hours, phone, tags, is_featured)
VALUES 
('MU沐光瑜珈運動空間', '桃園市 | 大溪區', 'https://maps.app.goo.gl/9Zp7q6m5z4x3c2v1b', '平日每日 10:00-22:00', '033808737', ARRAY['健身課程', '瑜珈', '體驗'], true),
('SUNNY 瑜珈健身俱樂部', '桃園市 | 桃園區', 'https://maps.app.goo.gl/1v2b3n4m5l6k7j8h9', '平日每日 10:00-22:00', '034991366', ARRAY['特色空間設施', '體驗'], true);
