-- 建立通知資料表
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    tag TEXT NOT NULL CHECK (tag IN ('活動', '課程', '公告', '優惠')),
    content TEXT NOT NULL,
    target_role TEXT NOT NULL CHECK (target_role IN ('student', 'coach', 'all')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 關閉 RLS 以便測試環境下直接讀寫（或者您可以設定具體的 Policy）
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;

-- 插入一些初始測試資料
INSERT INTO notifications (title, tag, content, target_role)
VALUES 
('春季瑜珈課程開跑', '課程', '新的春季瑜珈課程已經開放報名，歡迎各位學員參加。', 'student'),
('教練月度會議通知', '公告', '請所有教練於本週五下午兩點準時參加月度技術交流會議。', 'coach'),
('系統停機維護公告', '公告', '本週日凌晨 2:00 將進行系統升級維護，預計耗時 2 小時。', 'all');
