-- 更新活動資料表以支援更多欄位
ALTER TABLE events ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS link_url TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS label TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;

-- 註解：如果 events 表格尚未建立，請參考 init.sql
-- CREATE TABLE IF NOT EXISTS events (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     title TEXT NOT NULL,
--     subtitle TEXT,
--     content TEXT,
--     image_url TEXT,
--     link_url TEXT,
--     label TEXT,
--     category TEXT,
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );
